### ISSUE TITLE
[META] Automate the creation of the changes for a release

### ISSUE THREAD

**Issue by zero-24** [joomla/update.joomla.org#166]
## Problem statment

right now all that PRs that updates the XML files for a release require me to do all that manually. That means:
- update my local fork with the latest changes
- checkout a new branch
- manually update the XML
- commit & push
- and create a pull reqest.

All that require me to be at my development machine and taking care of them.
Right now i do them short after the release so the release do not depend on my personally.
But when there is an emergency release required i 'm might not be around to do the changes and the release manager hat to take that extra time to check and update the XML files.

## Proposed solution

My idea would be some kind of script / bot that runs on some kind of event (or can be triggered by an existing script that we use?)

That script would than do all the steps mention above and creates a pull request the release manager just has to review and merge.

The steps to take would be:
- pull the lastest changes from the update.joomla.org repo
- checkout a new branch
- run some regex over the XML files
- commit & push the changes
- create a PR by using the [GitHub API](https://developer.github.com/v3/pulls/#create-a-pull-request)
- optionally inform an Glip channel that the script ran succuessfully.

## Mentions

@wilsonge @HLeithner 

- What are your opinions on that? Do I start to over engineer the process here?
- Do you have any pointers for that event the bot could listen on? 
- Do you have a idea how to best integrate that bot?
-- Should it be a job manually to be started?
-- Another Idea could be that any pushed stable release tag triggers the bot that than creates the PR for the next release? So we push 3.9.19 and the bot does the update server changes for 3.9.20.
- Should we use a existing or a new dedicated github bot for that actions as he need no special access to could make sense to use a new dedicated account right?
- Any other feedback?

Thanks

**Comment by mbabker** [comment]
IMO you’re over-engineering something that should take no more than 5 minutes to take care of when you have all the info (all file hashes, versions, download URLs, .org article URL, etc.).  Yes it is tedious work to find all the info and get it into the files but realistically unless someone writes a Drone task (since you all seem to prefer that over any better known/supported CI) that can fully publish a release end-to-end then trying to automate this single step is honestly one of the least pressing matters.

**Comment by zero-24** [comment]
Ok thanks for the feedback :)

**Comment by zero-24** [comment]
Ok i just was thinking more about it. Would still be overengenieerd to create a bash script in this repo that would do the version changes and resets the hashes?

**Comment by HLeithner** [comment]
I already mentioned it in the chat many things you listed would be a bit over-engineering, but there are steps that can be automated.

I already adapted the build script to create the github tag entry and the update script for downloads.joomla.org. I don't speak with any api only create prepared txt files I only have to copy paste.

As soon as we get an automatic update process the complete build process changes anyway but that will not happen in the near future.

In the end you have to work with it and it should be good for you and more importantly secure.
