### ISSUE TITLE
update.joomla.org is IPv4 only

### ISSUE THREAD

**Issue by J0WI** [joomla/update.joomla.org#168]
There is no IPv6 route to update.joomla.org, so IPv6-only Joomla installations never receive updates.

**Comment by zero-24** [comment]
This is the response from Rochen.

> Thanks for your patience here. Would it be possible to provide the IP addresses for any affected visitors and/or their associated ISP? All internet service providers should support IPv4 (or IPv4 over IPv6) so there should be no problems accessing your sites without IPv6 functionality on the server. If those users can copy any errors received as well, that would be very helpful. 

Can you provide that info?

**Comment by J0WI** [comment]
There is no AAAA record for this domain. You should probably fix that first before you can debug routes to specific ISPs.

> All internet service providers should support IPv4 (or IPv4 over IPv6)

That's a wrong assumption. In cloud and container environments you can find providers that offer only IPv6 hosts or charge you an extra fee for IPv4. It' also hard for new ISPs to get any IPv4 addresses. There are some ugly workarounds, all of them having their own drawbacks.

IMHO "All internet service providers should support IPv6 **and** IPv4" is more accurate and so should yours.

**Comment by zero-24** [comment]
Just a quick update here i have been told this is right now beeing discussed with our hosting provider.

**Comment by zero-24** [comment]
Cc @HLeithner and @conconnl

**Comment by conconnl** [comment]
Our platform is being prepared to activated the DNS configuration per website.
We have to wait for the final activation by RIPE.
After this is done, we are going to active IPv6 site by site.

**Comment by gwsdesk** [comment]
By site? hmmmm Why not do this server wide?

**Comment by zero-24** [comment]
It is server wide but we have different servers ;)

**Comment by conconnl** [comment]
> By site? hmmmm Why not do this server wide?

4 servers are prepared, but the sites are done one by one on DNS Level.
You don't want to change the DNS for all sites at once, if anything go wrong, we have a bigger problem.

**Comment by gwsdesk** [comment]
in Cpanel you can set the DNS 'server-wide' for IPv-6 see https://docs.cpanel.net/knowledge-base/general-systems-administration/how-to-get-started-with-ipv6 or set them for individual accounts. If you do this properly nothing can go wrong   (unless you do not know what you are doing)

**Comment by zero-24** [comment]
> So it is kind of 'interesting' to learn that the Joomla site are running from (different 'shared'?) servers as mentioned above.

joomla.org runs on a different servers as the JED as they have different requirements. ;)
similiar appy to update.joomla.org that is a CDN and not a single server

> Why are we on different servers and not on a "Joomla-server" ? (it is very much related to cost savings and the issue at hand!)

The servers are managed by our hosting provider aka Rochen. That are all "joomla servers" but there are just more than one joomla server ;)

**Comment by gwsdesk** [comment]
Which is a waste of resources and funds by Joomla (Open Source Matters)  You do not need to run separate servers. That is old-fashioned especially when you have  good and proper image/backup system in place...

You can run the entire Joomla operations from a single secured Dedi server with proper image and restore options on SSD and (probably) save tons of money on hosting. Why are we so stupid ad keep loving history ties so much?

**Comment by zero-24** [comment]
> Which is a waste of resources and funds by Joomla (Open Source Matters) You do not need to run separate servers. That is old-fashioned especially when you have good and proper image/backup system in place...

Please be ashured that we know what we are doing and that the costs are covered by Rochen in that case and that the management part is done by rochen too.

**Comment by gwsdesk** [comment]
@zero-24 I doubt that mea culpa based on the fact that I am running a highly successful Joomla niche hosting company with 7K Joomla users. I do not adverse Rochen.... They have done a good job in the present/past for Joomla but I do think that we (!) as Joomla are to focused on past relations... (no worries... I do not wish to host Joomla for non-technical reasons).......We should open our eyes for better and cheaper options for our community .... If Rochen pays for the hosting I am well put back in my cage

**Comment by zero-24** [comment]
You have to put back your cage than.

**Comment by gwsdesk** [comment]
Hiding again ;-)

**Comment by gwsdesk** [comment]
Just 'ask' if questions are  arising from hosting for Joomla... My certified Linux Techs at GWS-Host.com will be glad to advise. For Joomla!.org sites we advise of course free of any charges!

**Comment by zero-24** [comment]
Thanks.

**Comment by brianteeman** [comment]
The cost from rochen is zero. If they want to use 99 servers so what.

**Comment by conconnl** [comment]
All our sites have been running IPv6 for a few weeks now.
@J0WI can you confirm it for the site you requested?

**Comment by J0WI** [comment]
`update.joomla.org` is not accessible over IPv6. There is no `AAAA` record.

**Comment by conconnl** [comment]
> `update.joomla.org` is not accessible over IPv6. There is no `AAAA` record.

It seems that this one is specifically connected to the CDN which doesn't support IPv6.
CloudFlare still hasn't responded to us after various requests to see if we could move our CDN to them via their Open Source sponsoring program.

**Comment by zero-24** [comment]
Looks like CloudFlare has been fully setup by now:
![image](https://user-images.githubusercontent.com/2596554/152698278-757c16c0-0cde-44cb-816c-7b225e7c9c03.png)
