### ISSUE TITLE
How do we handle the core and extensions Updates if downloads.joomla.org is live?

### ISSUE THREAD

**Issue by zero-24** [joomla/update.joomla.org#17]
I have noticed there is a branch about download.joomla.org but it looks not different: https://github.com/joomla/update.joomla.org/tree/downloads.joomla.org

So what is the plan if we get download.joomla.org live and how we handle core & com_joomlaupdate Updates than?

**Comment by mbabker** [comment]
That was there as a testing point from a while ago when we were trying to sort out SSL related issues with the update system.  It can be deleted for now.

**Comment by zero-24** [comment]
Ok i can do this later. But what is the plan about this repo if the downloads portal is live? I hope we hold the flexibility by do it manually.

**Comment by Bakual** [comment]
Deleted the branch :smile:

**Comment by zero-24** [comment]
:+1:

**Comment by mbabker** [comment]
> I hope we hold the flexibility by do it manually.

There aren't any update streams configured on the download site.  Honestly the way the XML files are structured right now it'd be too difficult to try and manage them via the download site.

Language files can probably use update streams, and if we ever get extensions loaded in there those could too.  But that's a long way off.

**Comment by zero-24** [comment]
:+1: Thanks for the feedback.
