### ISSUE TITLE
[4] no zip file for nightly build

### ISSUE THREAD

**Issue by alikon** [joomla/update.joomla.org#225]
https://developer.joomla.org/nightlies/Joomla_4.0.6-dev-Development-Update_Package.zip gives 404

**Comment by zero-24** [comment]
@wilsonge the version has to be reset to 4.0.6-dev in the version.php right now it is 4.0.6-rc3-dev ;-)

**Comment by wilsonge** [comment]
Think it’s fixed itself. Just needed a new nightly to have run in Jenkins after the RC release

**Comment by zero-24** [comment]
The version within the version.php still is rc3-dev and not just -dev so a new nighly build would not fix this. ;-)

**Comment by alikon** [comment]
still 404

**Comment by zero-24** [comment]
This thing has been sorted now we are updating the update server to the next rc build.
