### ISSUE TITLE
URGENT Joomla 4.1.4 Release https://update.joomla.org/core/sts/extension_sts.xml

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/update.joomla.org#248]
https://github.com/joomla/joomla-cms/issues/37879#issue-1246826020

**Comment by alikon** [comment]
see https://github.com/joomla/update.joomla.org/pull/249

**Comment by HLeithner** [comment]
Thanks

**Comment by PhilETaylor** [comment]
Is that it? Are you going to consider how to stop this repeating in the future? A simple xml lint GitHub action? Joomla has to stop making new history of failed releases - it’s getting embarrassing now - and people are rightly waiting days, weeks before updating because of the long history of release day issues.

**Comment by HLeithner** [comment]
We are in the progress of implementing tuf for joomla including half automatic releases.

**Comment by PhilETaylor** [comment]
I'll believe it when I see it. Joomla cannot even release correctly now, let alone with air-gapped cryptography signing... TUF has been talked about for almost a decade.
