### ISSUE TITLE
Testing update server Stability

### ISSUE THREAD

**Issue by brianteeman** [joomla/update.joomla.org#256]
Set the update server to Testing and the minimum stability to stable and I was being offered an RC - that was not expected.

![image](https://user-images.githubusercontent.com/1296369/174679761-517399f0-10f3-491b-b185-1f4abcb2d236.png)

Further checks suggest that the minimum stability setting does nothing for the Testing server

Is it because all the updates in https://update.joomla.org/core/test/extension_test.xml are marked as stable??

![image](https://user-images.githubusercontent.com/1296369/174679967-bed4cfa9-0009-40fe-bf23-4b493003d826.png)

**Comment by zero-24** [comment]
Yes it is a kind of know issue that we don't respect the setting but declare anything as "stable" to avoid issues people have when they switch to the "Testing Channel" but dont get any updates. For the core its a bit different as for extensions as we have dedicated update servers for testing.

When it would be only about me I'm fine to set the correct stability setting but I can also understand the reasons we have not done it in the past as it makes the testing barrier again a bit higher while we need more testers not less. ;)

**Comment by brianteeman** [comment]
ok - confused the hell out of me with it present and not working
