### ISSUE TITLE
On 3.2.7 i get update to ... 3.2.7

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/update.joomla.org#28]
On 3.2.7 installation with php 5.6.x i get update to ... 3.2.7.
There is something not correct with the xml in this case.

**Comment by zero-24** [comment]
Can you double check the caches? Can you show the screen of com_joomlaupdate?

**Comment by zero-24** [comment]
and which update server do you use ;)

**Comment by zero-24** [comment]
ok got it. it is a problem with the update XMLs I'm on a fix. Thanks!

**Comment by zero-24** [comment]
please see #29
