### ISSUE TITLE
Please enable the "Pages" mode for this repository.

### ISSUE THREAD

**Issue by korenevskiy** [joomla/update.joomla.org#286]
Please enable the "Pages" mode for this repository. For some reason, the IP of the update server is closed. Despite the fact that this repository is just responsible for updates. What requires PAGES mode enabled

https://github.com/apps/github-pages
Here ... https://github.com/joomla/update.joomla.org/settings/pages

**Comment by HLeithner** [comment]
We have our own update servers and doesn't use gh-pages. Why should we activate it?

**Comment by korenevskiy** [comment]
> We have our own update servers and doesn't use gh-pages. Why should we activate it?

Because amazon IP addresses are blocked in Russia. 
The update information is stored in 2 XML files.
https://update.joomla.org/core/sts/extension_sts.xml
```XML
<downloads>
	<downloadurl type="full" format="zip">https://downloads.joomla.org/cms/joomla4/4-2-8/Joomla_4.2.8-Stable-Update_Package.zip</downloadurl>
	<downloadsource type="full" format="zip">https://github.com/joomla/joomla-cms/releases/download/4.2.8/Joomla_4.2.8-Stable-Update_Package.zip</downloadsource>
	<downloadsource type="full" format="zip">https://update.joomla.org/releases/4.2.8/Joomla_4.2.8-Stable-Update_Package.zip</downloadsource>
</downloads>
```
The archive address in the first `<downloadurl>` tag is not available at all.
But at the same time, the addresses in the `<downloadsource>` tags are fully accessible.
Also the address below from `<downloadsource>` is fully accessible.
`https://update.joomla.org/releases/4.2.8/Joomla_4.2.8-Stable-Update_Package.zip`

**Comment by HLeithner** [comment]
Yes thats reason why we have downloadsource. But using github pages would not change anything in this behaviour

**Comment by korenevskiy** [comment]
> Yes thats reason why we have downloadsource. But using github pages would not change anything in this behaviour

https://github.com/korenevskiy/Joomla_Update_Russian
Updates from Pages Pages are fully working. Here is an example of a repository. It contains the same XML files, but only the links in them are rearranged in places. After that, we register the URL to the XML file in the Joomla settings.
The problem is that you have to manually update the XML files in the repository.

**Comment by korenevskiy** [comment]
Although you are right. I forgot the reason for blocking updates.
After all, the problem is in ZIP files. not in XML

**Comment by korenevskiy** [comment]
I'm sorry to bother you. But then what role do `<downloadsource>` tags play?

**Comment by HLeithner** [comment]
downloadsource will automatically be selected if downloading from the downloadurl fails.

**Comment by korenevskiy** [comment]
But it doesn't work. The transition to the alternative link does not occur. Thanks for the information. I will try to find the reason for the error of going to an alternative link.
