### ISSUE TITLE
Joomla! Nightly Build

### ISSUE THREAD

**Issue by Razzo1987** [joomla/update.joomla.org#297]
In https://update.joomla.org/core/nightlies/next_minor_extension.xml there is version 4.4.0-dev
but https://developer.joomla.org/nightlies/Joomla_4.4.0-dev-Development-Update_Package.zip is a 404

In https://developer.joomla.org/nightly-builds.html there is version 4.4.0-rc2-dev
the 2 link is valid:
* [Joomla_4.4.0-rc2-dev-Development-Full_Package.zip](https://developer.joomla.org/nightlies/Joomla_4.4.0-rc2-dev-Development-Full_Package.zip)
* [Joomla_4.4.0-rc2-dev-Development-Update_Package.zip](https://developer.joomla.org/nightlies/Joomla_4.4.0-rc2-dev-Development-Update_Package.zip)

-----

Same problem in https://update.joomla.org/core/nightlies/next_patch_extension.xml:
https://developer.joomla.org/nightlies/Joomla_4.3.2-dev-Development-Full_Package.zip is a 404

-----

It is possible to fix the version in xml?

**Comment by zero-24** [comment]
@laoneo can you please take a look here. In the best case the version within version.php should be 4.4.0-dev in the CMS repo. As no rc espacially rc2 has not been released yet. The Update server on that end looks correct to me but the version.php needs to be fixed.

**Comment by zero-24** [comment]
> Same problem in https://update.joomla.org/core/nightlies/next_patch_extension.xml:
https://developer.joomla.org/nightlies/Joomla_4.3.2-dev-Development-Full_Package.zip is a 404

That should fix itself as the release was done today and the version adjustments need to be propagated via the build process. cc @obuisard

**Comment by Razzo1987** [comment]
I think I had the same problem yesterday too. But I'm not sure. I'll check if it still shows up.

Thank you <3

**Comment by Razzo1987** [comment]
Yes, is fixed.
thanks!
