### ISSUE TITLE
Joomla! Nightly Build

### ISSUE THREAD

**Issue by Razzo1987** [joomla/update.joomla.org#323]
In https://update.joomla.org/core/nightlies/next_minor_extension.xml there is version 4.4.0-alpha5-dev
but https://developer.joomla.org/nightlies/Joomla_4.4.0-alpha5-dev-Development-Update_Package.zip is a 404

In https://developer.joomla.org/nightly-builds.html there is version 4.4.0-rc2-dev
the 2 link is valid:
* [Joomla_4.4.0-beta2-dev-Development-Full_Package.zip](https://developer.joomla.org/nightlies/Joomla_4.4.0-beta2-dev-Development-Full_Package.zip)
* [Joomla_4.4.0-beta2-dev-Development-Update_Package.zip](https://developer.joomla.org/nightlies/Joomla_4.4.0-beta2-dev-Development-Update_Package.zip)

It is possible to fix the version in xml?

**Comment by Razzo1987** [comment]
Oh, I see now the pull request https://github.com/joomla/update.joomla.org/pull/321

**Comment by HLeithner** [comment]
seems to be forgotten to merge, I merged it thanks
