### ISSUE TITLE
[update] Nightly build xml

### ISSUE THREAD

**Issue by 810** [joomla/update.joomla.org#35]
Update nightly builds xml:

now its taking the 3.7.0-dev2 build:
https://update.joomla.org/core/nightlies/next_minor_list.xml

**Comment by 810** [comment]
already a pr, closing this one.

**Comment by zero-24** [comment]
I can do a PR later. But as we have the alpha build it is not that critical ;) even as it is not a official way to update any system. As we do not official support any non-stable to non-stable or non-stable to stable updates ;)
