### ISSUE TITLE
On Joomla 3.4.3 I get direct update to 3.6.5

### ISSUE THREAD

**Issue by wojsmol** [joomla/update.joomla.org#41]
Hello
On the page based on Joomla! 3.4.3 and operating on php 5.6.x getting proposals to update directly to Joomla! 3.6.5. IMHO according to https://www.joomla.org/announcements/release-news/5666-the-joomla-3-6-1-update.html correct update path for this case are: 3.4.3-> 3.6.0 -> update com_joomlaupdate-> 3.6.5.
Regards

**Comment by zero-24** [comment]
You should be able to update from 3.4.3 to 3.6.5 as we have a fallback implemented in the newer versions. Or do you get an error message on updating?

**Comment by wojsmol** [comment]
> You should be able to update from 3.4.3 to 3.6.5 as we have a fallback implemented in the newer versions

@zero-24 Thank you for the information. Tomorrow will execute update and report any errors related to the lack of CSRF token.

**Comment by zero-24** [comment]
please just one a test install and not the live site ;)

**Comment by wojsmol** [comment]
A moment ago I made an update on a test server - everything goes without problems.

**Comment by zero-24** [comment]
Thanks for checking 👍
