### ISSUE TITLE
Updates prom Joomla! 2.5 brokrn 

### ISSUE THREAD

**Issue by wojsmol** [joomla/update.joomla.org#71]
Hi
On forum user reported that update from Joomla! 2.5 to 3. is broken. Looking in xml's user semes to be right

cc @zero-24 @mbabker

**Comment by zero-24** [comment]
Would be great to know what is broken and not just "it is broken".

> Looking in xml's user semes to be right

Would be great to know what you saw there ;)

Did this also fail by using: https://github.com/joomla/update.joomla.org/pull/70 / https://www.jah-tz.de/downloads/core/list_sts.xml

As 2.5 should point to 3.5.1 => 3.6.5 => 3.8.0

**Comment by wojsmol** [comment]
@zero-24 I'm in work now, shout version then:
1. This forum topic shroud be visible in my forum post, because I responded to it - few days back User reported that us impossible to update from 2.5 to 3.x.
2. I Check now official xml's and I see there is entry for 2.5 as seconf entry - that was the couse of my mistake when I checked xml's before.

**Comment by zero-24** [comment]
Any update to this? IMO after the latest changes everything should work (when there are no massive ressource problems too)

**Comment by wojsmol** [comment]
Hi @zero-24 
I tested today update from a fresh Joomla! 2.5.0 with sample data on my localhost and all run ok. Most probably user don't switch update channel to  Short term support. I used official update server.

**Comment by zero-24** [comment]
👍 Closing than.
