### ISSUE TITLE
Merge language cron job repo here

### ISSUE THREAD

**Issue by mbabker** [joomla/update.joomla.org#75]
Merge https://github.com/joomla-projects/language-update-xml-generator to this repo.  No point in having resources deployed on one server managed in two separate repositories.

**Comment by mbabker** [comment]
On the server this is deployed to a `translation-cli` directory that's parallel to the `www` directory so let's keep that same folder structure for simplicity.

**Comment by zero-24** [comment]
Please see: https://github.com/joomla/update.joomla.org/pull/76
